### PR TITLE
Consumer throws errors for body/cookie decoder

### PR DESCRIPTION
**Pull request by vishvish**
It's been changed for the latest connect package.

I fixed these lines:

```
connect.bodyParser(),
connect.cookieParser(),
```

### CODE REVIEW

**Comment by KirillTemnov** [comment]
New version of connect still have problems with compatibility

On example.com:3000 getting error

```
Error in request: { stack: [Getter/Setter], arguments: undefined, type: undefined, message: 'socket hang up' }
```

**Comment by vishvish** [comment]
How annoying. Any idea where the issue is down the stack? I'm also getting the error now that I've looked.

**Comment by KirillTemnov** [comment]
Need to read mugration issues on connect, I think problem's described there

**Comment by KirillTemnov** [comment]
the problem might be in headers,
I think we should change

```
res.writeHead(200, {'Content-Type': 'text/plain'});
```

to

```
 res.setHeader('Content-Type', 'text/plain');   
```

could you check this?

**Comment by vishvish** [comment]
Nah, didn't do anything. I have a strange feeling that in my case it's to do with OpenSSL not getting invoked. I'm running OS X 10.6.7, and while I had to modify the node install slightly, I did get it recognize OpenSSL second time round.

But the crypto module seems to return a blank on trying to get an HMAC.

**Pull request merged**
